In [6]:
import pandas as pd
import numpy as np
import boto3
import os
import io
from datetime import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
from pprint import pprint
from pandas.api.types import infer_dtype
from tqdm import tqdm

pd.set_option("display.max_rows", 1000)

In [24]:
class DataHandler:
    
    def __init__(self, s3_bucket, foldername):
        self.s3_bucket  = s3_bucket
        self.foldername = foldername
            
    def get_data(self, filename):
        s3 = boto3.client('s3')
        client = boto3.client('s3')
        obj = client.get_object(Bucket = self.s3_bucket, Key = self.foldername + "/" + filename)
        with io.BytesIO(obj['Body'].read()) as stream:
            df = pd.read_csv(stream, low_memory=False)
        return df

DH = DataHandler(s3_bucket  = "adamandrew-data", foldername = "Flights")

In [26]:
df_airlines = DH.get_data("airlines.csv")
df_airports = DH.get_data("airports.csv")
df_flights = DH.get_data("flights.csv")

print(len(df_airlines))
print(len(df_airports))
print(len(df_flights))

14
322
5819079

In [100]:
def prep_master_df(df_airlines, df_airports, df_flights):
    """
    uses inner joins due to missing joinas between source datasests
    mismatches due to non-domestic origin or destination
    """
    print("Renaming columns in airlines")
    df_airlines = df_airlines.rename(columns = {"AIRLINE": "AIRLINE_NAME"})\
        .progress_apply(lambda x: x)
    
    print("Merging flights with airlines")
    df_flights = pd.merge(
        left = df_flights, right = df_airlines,
        left_on = "AIRLINE", right_on = "IATA_CODE",
        how = "inner").drop(["AIRLINE"], axis = 1)\
        .progress_apply(lambda x: x)

    print("Cleaning latitude and longitude in airports")
    df_airports = df_airports[~df_airports["LATITUDE"].isnull() & ~df_airports["LONGITUDE"].isnull()]\
        .progress_apply(lambda x: x)
    
    print("Renaming columnas in airports origin")
    df_airports_orig = df_airports.rename(columns = {old: "ORIG_" + old for old in df_airports.columns})\
        .progress_apply(lambda x: x)
    
    print("Merging flights with airports origin")
    df_flights = pd.merge(
        left = df_flights, right = df_airports_orig,
        left_on = "ORIGIN_AIRPORT", right_on = "ORIG_IATA_CODE",
        how = "inner").drop(["ORIGIN_AIRPORT"], axis = 1)\
        .progress_apply(lambda x: x)
    
    print("Renaming columnas in airports destination")
    df_airports_dest = df_airports.rename(columns = {old: "DEST_" + old for old in df_airports.columns})\
        .progress_apply(lambda x: x)
    
    print("Merging flights with airports destination")
    df_flights = pd.merge(
        left = df_flights, right = df_airports_dest,
        left_on = "DESTINATION_AIRPORT", right_on = "DEST_IATA_CODE",
        how = "inner").drop(["DESTINATION_AIRPORT"], axis = 1)\
        .progress_apply(lambda x: x)
    
    
    # after inner joins, origin and destination countries all usa and year is always 2015 - removing
    df_flights = df_flights.drop(["YEAR", "ORIG_COUNTRY", "DEST_COUNTRY"], axis = 1)
    
    # very small number of nulls - removing
    df_flights = df_flights[~df_flights["SCHEDULED_TIME"].isnull()]
    
    df_flights["COUNTER"] = 1
    df_flights = df_flights.rename(columns = {
        "ARRIVAL_DELAY": "ARRIVAL_DELAY_MINS",
        "DEPARTURE_DELAY": "DEPARTURE_DELAY_MINS"
    })
    df_flights["ARRIVAL_DELAY_1H"] = df_flights["ARRIVAL_DELAY_MINS"].apply(lambda x: 1 if x >= 60 else 0)
    df_flights["DEPARTURE_DELAY_1H"] = df_flights["DEPARTURE_DELAY_MINS"].apply(lambda x: 1 if x >= 60 else 0)
    
    return df_flights

In [101]:
df = prep_master_df(df_airlines, df_airports, df_flights)

Renaming columns in airlines

100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 2607.59it/s]

Merging flights with airlines

100%|███████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 21.04it/s]

Cleaning latitude and longitude in airports

100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 7821.03it/s]

Renaming columnas in airports origin

100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 21604.21it/s]

Merging flights with airports origin

100%|███████████████████████████████████████████████████████████████████████████████████| 38/38 [00:02<00:00, 17.14it/s]

Renaming columnas in airports destination

100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 7624.03it/s]

Merging flights with airports destination

100%|███████████████████████████████████████████████████████████████████████████████████| 44/44 [00:02<00:00, 16.01it/s]

In [103]:
metadata = pd.DataFrame({"colname": df.columns, "rowcount": len(df)})
metadata["datatype"]  = metadata["colname"].apply(lambda x: infer_dtype(df[x]))
metadata["distinct"]  = metadata["colname"].apply(lambda x: len(df[x].unique()))
metadata["nullcount"] = metadata["colname"].apply(lambda x: df[x].isnull().sum())
metadata["nullperc"]  = metadata.apply(lambda x: np.round(x["nullcount"] / x["rowcount"] * 100, 2), axis = 1)

In [104]:
metadata

                 colname  rowcount  datatype  distinct  nullcount  nullperc
0                  MONTH   5323693   integer        11          0      0.00
1                    DAY   5323693   integer        31          0      0.00
2            DAY_OF_WEEK   5323693   integer         7          0      0.00
3          FLIGHT_NUMBER   5323693   integer      6952          0      0.00
4            TAIL_NUMBER   5323693    string      4897      14349      0.27
5    SCHEDULED_DEPARTURE   5323693   integer      1317          0      0.00
6         DEPARTURE_TIME   5323693  floating      1441      83756      1.57
7   DEPARTURE_DELAY_MINS   5323693  floating      1198      83756      1.57
8               TAXI_OUT   5323693  floating       185      86553      1.63
9             WHEELS_OFF   5323693  floating      1441      86553      1.63
10        SCHEDULED_TIME   5323693  floating       544          0      0.00
11          ELAPSED_TIME   5323693  floating       712     101693      1.91
12              AIR_TIME   5323693  floating       676     101693      1.91
13              DISTANCE   5323693   integer      1359          0      0.00
14             WHEELS_ON   5323693  floating      1441      89872      1.69
15               TAXI_IN   5323693  floating       186      89872      1.69
16     SCHEDULED_ARRIVAL   5323693   integer      1433          0      0.00
17          ARRIVAL_TIME   5323693  floating      1441      89872      1.69
18    ARRIVAL_DELAY_MINS   5323693  floating      1222     101693      1.91
19              DIVERTED   5323693   integer         2          0      0.00
20             CANCELLED   5323693   integer         2          0      0.00
21   CANCELLATION_REASON   5323693    string         5    5236327     98.36
22      AIR_SYSTEM_DELAY   5323693  floating       564    4321770     81.18
23        SECURITY_DELAY   5323693  floating       155    4321770     81.18
24         AIRLINE_DELAY   5323693  floating      1042    4321770     81.18
25   LATE_AIRCRAFT_DELAY   5323693  floating       691    4321770     81.18
26         WEATHER_DELAY   5323693  floating       622    4321770     81.18
27             IATA_CODE   5323693    string        14          0      0.00
28          AIRLINE_NAME   5323693    string        14          0      0.00
29        ORIG_IATA_CODE   5323693    string       319          0      0.00
30          ORIG_AIRPORT   5323693    string       319          0      0.00
31             ORIG_CITY   5323693    string       305          0      0.00
32            ORIG_STATE   5323693    string        54          0      0.00
33         ORIG_LATITUDE   5323693  floating       319          0      0.00
34        ORIG_LONGITUDE   5323693  floating       319          0      0.00
35        DEST_IATA_CODE   5323693    string       319          0      0.00
36          DEST_AIRPORT   5323693    string       319          0      0.00
37             DEST_CITY   5323693    string       305          0      0.00
38            DEST_STATE   5323693    string        54          0      0.00
39         DEST_LATITUDE   5323693  floating       319          0      0.00
40        DEST_LONGITUDE   5323693  floating       319          0      0.00
41               COUNTER   5323693   integer         1          0      0.00
42      ARRIVAL_DELAY_1H   5323693   integer         2          0      0.00
43    DEPARTURE_DELAY_1H   5323693   integer         2          0      0.00

In [109]:
# canceled, diverted, delayed_departure, delayed_arrival
pd.pivot_table(
    data    = df,
    columns = "ARRIVAL_DELAY_1H",
    index   = "TAXI_OUT",
    values  = "COUNTER",
    aggfunc = len
)

ARRIVAL_DELAY_1H         0        1
TAXI_OUT
1.0                  186.0     20.0
2.0                  308.0     18.0
3.0                 1499.0     86.0
4.0                 5296.0    316.0
5.0                20342.0   1015.0
6.0                65856.0   3213.0
7.0               140298.0   6934.0
8.0               228265.0  11032.0
9.0               313977.0  15389.0
10.0              375092.0  18271.0
11.0              402063.0  19766.0
12.0              402655.0  20191.0
13.0              382299.0  19357.0
14.0              350095.0  18063.0
15.0              311213.0  16448.0
16.0              271047.0  14640.0
17.0              234246.0  12988.0
18.0              200347.0  11444.0
19.0              170471.0   9952.0
20.0              144707.0   8827.0
21.0              123215.0   7699.0
22.0              104959.0   6920.0
23.0               89047.0   6033.0
24.0               75342.0   5413.0
25.0               64862.0   4765.0
26.0               55642.0   4436.0
27.0               47303.0   3886.0
28.0               40744.0   3494.0
29.0               35308.0   3345.0
30.0               30275.0   3040.0
31.0               26625.0   2733.0
32.0               23152.0   2455.0
33.0               20415.0   2312.0
34.0               17916.0   2083.0
35.0               15720.0   1945.0
36.0               14120.0   1845.0
37.0               12522.0   1755.0
38.0               11046.0   1593.0
39.0                9943.0   1568.0
40.0                8684.0   1364.0
41.0                7856.0   1286.0
42.0                6901.0   1204.0
43.0                6313.0   1176.0
44.0                5598.0   1051.0
45.0                5035.0   1062.0
46.0                4523.0   1017.0
47.0                4124.0    897.0
48.0                3722.0    897.0
49.0                3462.0    866.0
50.0                3136.0    808.0
51.0                2743.0    758.0
52.0                2495.0    730.0
53.0                2257.0    719.0
54.0                2101.0    699.0
55.0                1904.0    626.0
56.0                1698.0    603.0
57.0                1498.0    554.0
58.0                1412.0    579.0
59.0                1315.0    530.0
60.0                1175.0    492.0
61.0                1024.0    510.0
62.0                1005.0    516.0
63.0                 866.0    459.0
64.0                 885.0    444.0
65.0                 709.0    445.0
66.0                 704.0    408.0
67.0                 628.0    424.0
68.0                 543.0    380.0
69.0                 544.0    363.0
70.0                 488.0    366.0
71.0                 444.0    360.0
72.0                 392.0    370.0
73.0                 385.0    395.0
74.0                 358.0    314.0
75.0                 310.0    341.0
76.0                 265.0    333.0
77.0                 275.0    309.0
78.0                 227.0    279.0
79.0                 191.0    309.0
80.0                 173.0    285.0
81.0                 156.0    281.0
82.0                 145.0    315.0
83.0                 146.0    269.0
84.0                 129.0    252.0
85.0                 110.0    234.0
86.0                  85.0    245.0
87.0                  91.0    266.0
88.0                  67.0    277.0
89.0                  60.0    234.0
90.0                  56.0    209.0
91.0                  46.0    240.0
92.0                  45.0    212.0
93.0                  39.0    210.0
94.0                  28.0    184.0
95.0                  32.0    193.0
96.0                  25.0    198.0
97.0                  17.0    166.0
98.0                  19.0    163.0
99.0                  17.0    193.0
100.0                 14.0    174.0
101.0                  8.0    149.0
102.0                 14.0    149.0
103.0                 13.0    140.0
104.0                  5.0    129.0
105.0                 12.0    126.0
106.0                  9.0    157.0
107.0                  2.0    118.0
108.0                  3.0    105.0
109.0                  4.0    130.0
110.0                  4.0    104.0
111.0                  2.0    114.0
112.0                  7.0     98.0
113.0                  3.0    117.0
114.0                  3.0     89.0
115.0                  6.0    102.0
116.0                  4.0     97.0
117.0                  1.0     77.0
118.0                  2.0     68.0
119.0                  NaN     76.0
120.0                  NaN     97.0
121.0                  NaN     69.0
122.0                  4.0     77.0
123.0                  NaN     62.0
124.0                  NaN     73.0
125.0                  1.0     64.0
126.0                  2.0     51.0
127.0                  NaN     53.0
128.0                  NaN     52.0
129.0                  1.0     51.0
130.0                  1.0     52.0
131.0                  1.0     48.0
132.0                  NaN     41.0
133.0                  NaN     29.0
134.0                  1.0     34.0
135.0                  NaN     36.0
136.0                  NaN     33.0
137.0                  NaN     36.0
138.0                  NaN     26.0
139.0                  NaN     30.0
140.0                  1.0     28.0
141.0                  NaN     32.0
142.0                  NaN     37.0
143.0                  1.0     26.0
144.0                  1.0     17.0
145.0                  1.0     23.0
146.0                  1.0     23.0
147.0                  NaN     10.0
148.0                  NaN     19.0
149.0                  NaN     19.0
150.0                  NaN     14.0
151.0                  NaN     24.0
152.0                  NaN     10.0
153.0                  NaN     21.0
154.0                  NaN      9.0
155.0                  NaN      7.0
156.0                  NaN     11.0
157.0                  1.0      2.0
158.0                  NaN      7.0
159.0                  NaN     10.0
160.0                  NaN      5.0
161.0                  NaN      7.0
162.0                  NaN      4.0
163.0                  NaN      2.0
164.0                  NaN      9.0
165.0                  NaN      3.0
166.0                  NaN      2.0
167.0                  1.0      3.0
168.0                  NaN      2.0
169.0                  NaN      1.0
170.0                  NaN      3.0
171.0                  1.0      3.0
172.0                  NaN      4.0
173.0                  NaN      1.0
174.0                  NaN      3.0
175.0                  NaN      2.0
176.0                  NaN      1.0
177.0                  NaN      3.0
178.0                  NaN      1.0
179.0                  NaN      1.0
180.0                  NaN      1.0
181.0                  NaN      1.0
185.0                  NaN      1.0
200.0                  NaN      1.0
225.0                  NaN      1.0